sonar.projectKey=sw5005-sus_ceramicraft-secure
sonar.organization=sw5005-sus


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ceramicraft-secure
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.test.inclusions=enc/*_test.go,sign/*_test.go,api_test.go
sonar.test.exclusions=vault/**,**/test/**