// Code generated by MockGen. DO NOT EDIT.
// Source: key_manager.go
//
// Generated by this command:
//
//	mockgen -source=key_manager.go -destination=mock_key_manager.go -package=vault
//

// Package vault is a generated GoMock package.
package vault

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIKeyManager is a mock of IKeyManager interface.
type MockIKeyManager struct {
	ctrl     *gomock.Controller
	recorder *MockIKeyManagerMockRecorder
	isgomock struct{}
}

// MockIKeyManagerMockRecorder is the mock recorder for MockIKeyManager.
type MockIKeyManagerMockRecorder struct {
	mock *MockIKeyManager
}

// NewMockIKeyManager creates a new mock instance.
func NewMockIKeyManager(ctrl *gomock.Controller) *MockIKeyManager {
	mock := &MockIKeyManager{ctrl: ctrl}
	mock.recorder = &MockIKeyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKeyManager) EXPECT() *MockIKeyManagerMockRecorder {
	return m.recorder
}

// GetLatestVersion mocks base method.
func (m *MockIKeyManager) GetLatestVersion() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLatestVersion indicates an expected call of GetLatestVersion.
func (mr *MockIKeyManagerMockRecorder) GetLatestVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockIKeyManager)(nil).GetLatestVersion))
}

// GetSecConfigByKey mocks base method.
func (m *MockIKeyManager) GetSecConfigByKey(key string, version int) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecConfigByKey", key, version)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecConfigByKey indicates an expected call of GetSecConfigByKey.
func (mr *MockIKeyManagerMockRecorder) GetSecConfigByKey(key, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecConfigByKey", reflect.TypeOf((*MockIKeyManager)(nil).GetSecConfigByKey), key, version)
}
