// Code generated by MockGen. DO NOT EDIT.
// Source: vault_client.go
//
// Generated by this command:
//
//	mockgen -source=vault_client.go -destination=mock_vault_client.go -package=vault
//

// Package vault is a generated GoMock package.
package vault

import (
	context "context"
	reflect "reflect"

	api "github.com/hashicorp/vault/api"
	gomock "go.uber.org/mock/gomock"
)

// MockIVaultProxy is a mock of IVaultProxy interface.
type MockIVaultProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIVaultProxyMockRecorder
	isgomock struct{}
}

// MockIVaultProxyMockRecorder is the mock recorder for MockIVaultProxy.
type MockIVaultProxyMockRecorder struct {
	mock *MockIVaultProxy
}

// NewMockIVaultProxy creates a new mock instance.
func NewMockIVaultProxy(ctrl *gomock.Controller) *MockIVaultProxy {
	mock := &MockIVaultProxy{ctrl: ctrl}
	mock.recorder = &MockIVaultProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVaultProxy) EXPECT() *MockIVaultProxyMockRecorder {
	return m.recorder
}

// GetVersion mocks base method.
func (m *MockIVaultProxy) GetVersion(ctx context.Context, engineName, secPath string, version int) (*api.KVSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, engineName, secPath, version)
	ret0, _ := ret[0].(*api.KVSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockIVaultProxyMockRecorder) GetVersion(ctx, engineName, secPath, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockIVaultProxy)(nil).GetVersion), ctx, engineName, secPath, version)
}

// GetVersionsAsList mocks base method.
func (m *MockIVaultProxy) GetVersionsAsList(ctx context.Context, engineName, secPath string) ([]api.KVVersionMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionsAsList", ctx, engineName, secPath)
	ret0, _ := ret[0].([]api.KVVersionMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionsAsList indicates an expected call of GetVersionsAsList.
func (mr *MockIVaultProxyMockRecorder) GetVersionsAsList(ctx, engineName, secPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionsAsList", reflect.TypeOf((*MockIVaultProxy)(nil).GetVersionsAsList), ctx, engineName, secPath)
}
